name: MineSkinAPI
version: 1.0.5-RELEASE
author: DrKapdor
main: me.drkapdor.mineskinsapi.paper.MineSkinPaperPlugin
api-version: 1.16
description: Программный интерфейс взаимодействия с сервисами MineSkin
